plugins {
    id 'java-library'
}

dependencies {
    implementation project(':base')
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.ai:spring-ai-starter-model-google-genai'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation testFixtures(project(':base'))
}
